apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: 124058707612.dkr.ecr.us-east-2.amazonaws.com/virat/final-project:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
